import type { Metadata } from "next";
import { Jaini } from "next/font/google";
import "./globals.css";
import { BACKGROUND, FOREGROUND } from "../lib/colors";
import Providers from "@/components/Providers";
import Header from "@/components/Header";

const jaini = Jaini({
  variable: "--font-jaini",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jaini.variable} style={{ backgroundColor: BACKGROUND, color: FOREGROUND }}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
